# Generated by Django 2.1.5 on 2022-10-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
